version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  target-branch: master
  reviewers:
  - jimcavoli
  ignore:
  - dependency-name: activesupport
    versions:
    - 5.2.4.5
  - dependency-name: fastimage
    versions:
    - 2.2.1
    - 2.2.2
  - dependency-name: backports
    versions:
    - 3.20.2
  - dependency-name: minitest
    versions:
    - 5.14.3
  - dependency-name: ffi
    versions:
    - 1.14.2
