version: 1
update_configs:
  - package_manager: "ruby:bundler"
    directory: "/"
    update_schedule: "live"
    target_branch: "master"
    allowed_updates:
      - match:
          update_type: "all"
    version_requirement_updates: "auto"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "security:patch"
    default_reviewers:
      - "jimcavoli"
